Get to the point where we can do a clean plan with terraform0.13
Or at least, as far as it telling us that we need to upgrade to the
latest version of terraform:

    Error: state snapshot was created by Terraform v0.14.8, which is
    newer than current v0.13.5; upgrade to Terraform v0.14.8 or greater
    to work with this state